# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squrls',
            fields=[
                ('squrl_id', models.AutoField(primary_key=True, serialize=False)),
                ('squrl', models.SlugField(unique=True)),
                ('target', models.URLField(unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('access_date', models.DateTimeField(auto_now=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
